name = "sip" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
node_compat = true
workers_dev = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
PROXYIP = "43.218.79.114:2053"
UUID = "0a2ee030-101b-4985-b1e5-95c15fcf6ff7"
